name: CI

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - master # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          # build
          mkdir target && cd target && df -h > df.txt && free -g > free.txt && cat /proc/cpuinfo > cpuinfo.txt

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-folder
          path: target/
